### ISSUE TITLE
No security policy

### ISSUE THREAD

**Issue by ggurbet** [a3mc/helperbot#23]
Hello @uchu. I am doing the review for your project on CRDAO and your repository does not include a Security Policy, which is needed for the review to pass. Can you prepare one?

**Comment by uchu** [comment]
Sure, will update it later today. Is there any specific format that is approved as a standard now?

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by ggurbet** [comment]
You can just use GitHub's template to create one. Be sure to include how people could reach out to you.

Also, can you add me on Telegram [@ggurbet](https://t.me/ggurbet) so we can test the bot?

**Comment by uchu** [comment]
Sounds good. Will add it. I will be back to my laptop in a couple of hours and will contact you on telegram. Thanks a lot for working on the review

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by uchu** [comment]
Added it.
